# Generated by Django 3.1.1 on 2020-10-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourThoughts', '0002_auto_20200917_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Birthday',
            field=models.DateField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email_id',
            field=models.EmailField(max_length=65),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_nu',
            field=models.CharField(max_length=15),
        ),
    ]
