# Generated by Django 3.1.1 on 2020-10-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourThoughts', '0003_auto_20201008_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_nu',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
