# Generated by Django 3.1.1 on 2020-10-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourThoughts', '0004_auto_20201013_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_id',
            field=models.EmailField(max_length=65),
        ),
    ]
