# Generated by Django 3.1.1 on 2020-10-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YourThoughts', '0005_auto_20201013_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Birthday',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
